apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels: 
    tier: backend
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
    api: {{ .Values.name }}
