name: Destroy Azure infrastructure 

on: workflow_dispatch 

defaults:
  run:
    shell: bash
    working-directory: infra/terraform/

env:
  terraform_dir: ${{github.workspace}}/infra/terraform

jobs:

    destroy_azure_infra:
      
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Blob Storage - Download Blob
        uses: armanrahman22/azblob-download-action
        with:
          storage-account-name: "storage_rg"
          container-name: "carrentalservicestorage"
          blob-name: "terraform.tfstate"
          download-path: ${{env.terraform_dir}}/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        
      - name: Terraform destroy
        run: terraform destroy --target azurerm_kubernetes_cluster.aks
